17:23:40,853 (main) INFO  [org.apache.jdo.tck] - Exception during setUp or runtest: 
javax.jdo.JDOFatalException: Caught NamingException trying to bind Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:106) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.AbstractGetPMF.checkGetPMFWithInvalidProperties(AbstractGetPMF.java:117) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.testInvalidGetPMF(GetPMFByJNDILocation.java:75) ~[datastoreidentity/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:177) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:278) ~[classes/:?]
	at junit.framework.TestResult$1.protect(TestResult.java:122) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.runProtected(TestResult.java:142) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.run(TestResult.java:125) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestCase.run(TestCase.java:130) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.textui.TestRunner.doRun(TestRunner.java:116) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140) ~[classes/:?]
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:760) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:96) ~[datastoreidentity/:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.fscontext.RefFSContextFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96) ~[?:?]
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:757) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:96) ~[datastoreidentity/:?]
	... 20 more
17:23:40,873 (main) INFO  [org.apache.jdo.tck] - Exception during setUp or runtest: 
javax.jdo.JDOFatalException: Caught NamingException trying to bind Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:106) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.AbstractGetPMF.checkGetPMFWithValidProperties(AbstractGetPMF.java:133) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.testValidGetPMF(GetPMFByJNDILocation.java:85) ~[datastoreidentity/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:177) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:278) ~[classes/:?]
	at junit.framework.TestResult$1.protect(TestResult.java:122) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.runProtected(TestResult.java:142) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.run(TestResult.java:125) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestCase.run(TestCase.java:130) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.textui.TestRunner.doRun(TestRunner.java:116) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140) ~[classes/:?]
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:760) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:96) ~[datastoreidentity/:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.fscontext.RefFSContextFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96) ~[?:?]
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:757) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocation.getPMF(GetPMFByJNDILocation.java:96) ~[datastoreidentity/:?]
	... 20 more
17:23:40,878 (main) INFO  [org.apache.jdo.tck] - Exception during setUp or runtest: 
javax.jdo.JDOFatalException: 
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:105) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.AbstractGetPMF.checkGetPMFWithInvalidProperties(AbstractGetPMF.java:117) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.testInvalidGetPMF(GetPMFByJNDILocationAndClassLoader.java:75) ~[datastoreidentity/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:177) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:278) ~[classes/:?]
	at junit.framework.TestResult$1.protect(TestResult.java:122) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.runProtected(TestResult.java:142) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.run(TestResult.java:125) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestCase.run(TestCase.java:130) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.textui.TestRunner.doRun(TestRunner.java:116) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140) ~[classes/:?]
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:760) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:96) ~[datastoreidentity/:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.fscontext.RefFSContextFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96) ~[?:?]
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:757) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:96) ~[datastoreidentity/:?]
	... 20 more
17:23:40,889 (main) INFO  [org.apache.jdo.tck] - Exception during setUp or runtest: 
javax.jdo.JDOFatalException: 
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:105) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.AbstractGetPMF.checkGetPMFWithValidProperties(AbstractGetPMF.java:133) ~[datastoreidentity/:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.testValidGetPMF(GetPMFByJNDILocationAndClassLoader.java:85) ~[datastoreidentity/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at junit.framework.TestCase.runTest(TestCase.java:177) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:278) ~[classes/:?]
	at junit.framework.TestResult$1.protect(TestResult.java:122) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.runProtected(TestResult.java:142) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestResult.run(TestResult.java:125) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestCase.run(TestCase.java:130) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.runTest(TestSuite.java:241) ~[junit-4.13.2.jar:4.13.2]
	at junit.framework.TestSuite.run(TestSuite.java:236) ~[junit-4.13.2.jar:4.13.2]
	at junit.textui.TestRunner.doRun(TestRunner.java:116) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169) ~[classes/:?]
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140) ~[classes/:?]
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.fscontext.RefFSContextFactory
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:760) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:96) ~[datastoreidentity/:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.fscontext.RefFSContextFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133) ~[?:?]
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96) ~[?:?]
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:757) ~[?:?]
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722) ~[?:?]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
	at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
	at javax.naming.InitialContext.<init>(InitialContext.java:184) ~[?:?]
	at org.apache.jdo.tck.api.persistencemanagerfactory.GetPMFByJNDILocationAndClassLoader.getPMF(GetPMFByJNDILocationAndClassLoader.java:96) ~[datastoreidentity/:?]
	... 20 more
